/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviereviewapp;

import javax.swing.table.DefaultTableModel;
import javax.swing.event.TableModelListener;
import javax.swing.event.TableModelEvent;

/**
 *
 * @author Alex
 */
public class MoviePanel extends javax.swing.JPanel {

    private MovieManager mm = new MovieManager();
    private AddMovieFrame amf = new AddMovieFrame(this);
    boolean updatingTable = false;

    /**
     * Creates new form MoviePanel
     */
    public MoviePanel() {
        initComponents();
        refreshGUITable();

        this.movieTable.getModel().addTableModelListener(new TableModelListener() {

            public void tableChanged(TableModelEvent e) {
                if (updatingTable) {
                    return;
                }
                int changedRow = e.getFirstRow();
                Movie m = new Movie(Integer.parseInt(movieTable.getValueAt(changedRow, 0).toString()),
                        movieTable.getValueAt(changedRow, 1).toString(), movieTable.getValueAt(changedRow, 2).toString(),
                        movieTable.getValueAt(changedRow, 3).toString());
                mm.editMovie(m);
                refreshGUITable();
            }
        });

    }

    public void refreshGUITable() {

        updatingTable = true;

        //remove all the existing rows from gui table
        while (movieTable.getModel().getRowCount() > 0) {
            ((DefaultTableModel) (movieTable.getModel())).removeRow(0);
        }

        //get array of movies in movietbl
        Movie[] m = mm.getMovies();

        //update gui table with array
        for (int i = 0; i < m.length; i++) {
            addMovieToGUITable(m[i]);
        }
        
        updatingTable = false;
    }

    public void addMovieToGUITable(Movie m) {
        ((DefaultTableModel) (movieTable.getModel())).addRow(new Object[]{m.getID(), m.getName(), m.getDirector(), m.getDateOfRelease()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        movieTable = new javax.swing.JTable();
        addMovieButton = new javax.swing.JButton();
        deleteMovieButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        movieTable.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        movieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idMovies", "Movie Name", "Director", "Date of Release"
            }
        ));
        movieTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                movieTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(movieTable);

        addMovieButton.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        addMovieButton.setText("ADD");
        addMovieButton.setToolTipText("");
        addMovieButton.setInheritsPopupMenu(true);
        addMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieButtonActionPerformed(evt);
            }
        });

        deleteMovieButton.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        deleteMovieButton.setText("DELETE");
        deleteMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMovieButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Josefin Sans", 0, 14)); // NOI18N
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePackage/mpvoe.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteMovieButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addMovieButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addMovieButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteMovieButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void movieTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_movieTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieTableKeyPressed

    private void addMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovieButtonActionPerformed
        // TODO add your handling code here:
        amf.setBounds(0, 0, amf.getWidth(), amf.getHeight());
        amf.setVisible(true);

    }//GEN-LAST:event_addMovieButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refreshGUITable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMovieButtonActionPerformed
        // TODO add your handling code here:
        int[] id = movieTable.getSelectedRows();
        Movie[] arr = mm.getMovies();
        for (int i : id) {
            for (Movie m : arr) {
                if (m.getID() == Integer.parseInt((movieTable.getModel().getValueAt(i, 0)).toString())) {
                    mm.deleteMovie(m);
                    break;
                }
            }
        }
        refreshGUITable();
    }//GEN-LAST:event_deleteMovieButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMovieButton;
    private javax.swing.JButton deleteMovieButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable movieTable;
    // End of variables declaration//GEN-END:variables
}
